id: rule-skill-build-gate
scope: skill
intent: enforce-skill-creation-standards
version: "1.0"
description: |
  /build -g skill 创建新技能时的强制门禁。
  - 禁止创建 L0 入口技能（L0 已冻结，只能修改不能新增）
  - 创建后必须通过调用测试
  - 测试通过后必须写入 knowledge 卡片

triggers:
  - output_type: skill
  - keywords: [skill, cap, path, rule]

rules:
  # Rule 1: L0 创建禁令
  no-l0-creation:
    severity: BLOCK
    message: |
      ⛔ 禁止通过 /build -g skill 创建 L0 入口技能。
      L0 已冻结（9个命令），新能力只能作为 L1 path 或 L2 atom 添加。
      允许的类型: L1 path-*, L2 cap-*, cross-cutting rule-*
    check: |
      如果用户请求创建 L0 / entry / 顶层 SKILL.md:
        → 拒绝，提示改为 L1 path 或 L2 atom
        → 建议: "你需要的能力应该挂在某个现有 L0 下面作为 path 或 atom"

  # Rule 2: 调用测试
  invocation-test:
    severity: BLOCK
    message: |
      创建完成后必须验证技能可被正确调用:
      - L2 atom (cap-*): 通过 resolver 查找确认 capability-catalog.yaml 已注册
      - L1 path: 确认 _paths/CATALOG.md 已更新，YAML 格式正确
      - rule-*: 确认 _policies/ 下文件存在且 YAML 合法
      - 运行 bash tools/setup.sh 部署
      - 运行 bash tools/validate_contracts.sh 验证 contract
    check: |
      1. setup.sh 输出无 FAIL
      2. validate_contracts.sh 无报错（如存在）
      3. L2: grep cap-id 在 capability-catalog.yaml 中能找到
      4. L1: grep path-id 在 _paths/CATALOG.md 中能找到

  # Rule 3: 知识沉淀
  knowledge-capture:
    severity: BLOCK
    message: |
      测试通过后，必须写入知识卡片:
      - L1 path → knowledge/3-layer-skill/L1/<path-id>.md
      - L2 atom → knowledge/3-layer-skill/L2/<cap-id>.md
      - rule-*  → knowledge/3-layer-skill/L2/<rule-id>.md
    template: |
      # <cap-id / path-id>

      > Created: <date>
      > Layer: L1|L2
      > Status: tested-ok

      ## 做什么
      <一句话>

      ## 输入 → 输出
      <inputs> → <outputs>

      ## 调用方式
      ```
      <通过哪个 L0 命令 + 什么参数能触发到这个能力>
      ```

      ## 测试证据
      - setup.sh: OK
      - capability-catalog / CATALOG: 已注册
      - 调用验证: <具体验证命令和结果>

knowledge_base: /home/swei20/repos/claude-skills/claude-skills-private/knowledge/3-layer-skill
