#!/bin/bash
# Build Capability Catalog (FDPS v4)
# Regenerates _resolver/capability-catalog.yaml from block files in _caps/core/.
#
# All entries use cap-<verb>-<object> format.
# Files with YAML frontmatter cap_id are marked with cap_contract: true.
#
# Usage: bash tools/build_capability_catalog.sh [--verify] [--stats]

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_DIR/skills"
CATALOG_FILE="$SKILLS_DIR/_resolver/capability-catalog.yaml"
CAPS_DIR="$SKILLS_DIR/_caps/core"

# --- Flags ---
VERIFY_ONLY=false
STATS_ONLY=false
if [ "${1:-}" = "--verify" ]; then
  VERIFY_ONLY=true
elif [ "${1:-}" = "--stats" ]; then
  STATS_ONLY=true
fi

if [ "$STATS_ONLY" = true ]; then
  echo "=== Capability Catalog Stats ==="
  total=$(find "$CAPS_DIR" -name "*.md" -type f 2>/dev/null | wc -l)
  with_contract=$(find "$CAPS_DIR" -name "*.md" -type f -exec head -1 {} \; | grep -c '^---$' || true)
  echo "Total capability files: $total"
  echo "With frontmatter contract: $with_contract"
  echo "Without frontmatter: $((total - with_contract))"
  exit 0
fi

if [ "$VERIFY_ONLY" = true ]; then
  echo "=== Verify Capability Catalog ==="
  ERRORS=0

  # Check catalog exists
  if [ ! -f "$CATALOG_FILE" ]; then
    echo "  FAIL: capability-catalog.yaml not found"
    exit 1
  fi

  # Check all caps in catalog have existing block files
  while IFS= read -r block_path; do
    full_path="$SKILLS_DIR/$block_path"
    if [ ! -f "$full_path" ]; then
      echo "  FAIL: Block file not found: $block_path"
      ERRORS=$((ERRORS + 1))
    fi
  done < <(grep 'block:' "$CATALOG_FILE" | sed 's/.*block: *"//' | sed 's/".*//')

  # Check all .md files in _caps/core/ are referenced in catalog
  for md_file in "$CAPS_DIR"/*.md; do
    [ -f "$md_file" ] || continue
    filename=$(basename "$md_file")
    if ! grep -q "$filename" "$CATALOG_FILE" 2>/dev/null; then
      echo "  WARNING: $filename not referenced in catalog"
    fi
  done

  if [ "$ERRORS" -eq 0 ]; then
    echo "  PASS — All catalog entries verified"
    exit 0
  else
    echo "  FAIL — $ERRORS errors found"
    exit 1
  fi
fi

echo "=== Build Capability Catalog ==="
echo "Caps dir: $CAPS_DIR"
echo "Output: $CATALOG_FILE"
echo ""

# Ensure directories exist
mkdir -p "$SKILLS_DIR/_resolver"

# Header
cat > "$CATALOG_FILE" << 'HEADER'
# Capability Catalog v4.0 — FDPS Architecture (Public Core)
# Single source of truth for all capability metadata
# Auto-generated by tools/build_capability_catalog.sh
#
# Schema per entry (~35 tokens):
#   title, domain, stage, verb, object, triggers?,
#   input_types, output_types, leveling, summary?,
#   block (new _caps/ path), policies?, cap_contract?

version: '4.0.0'

capabilities:
HEADER

CAP_COUNT=0
CONTRACT_COUNT=0

# Group by stage for readability
declare -A STAGE_CAPS
STAGES=(discover decide build verify deliver operate review knowledge)

for md_file in "$CAPS_DIR"/*.md; do
  [ -f "$md_file" ] || continue
  filename=$(basename "$md_file" .md)
  block_path="_caps/core/$filename.md"

  # Check if file has YAML frontmatter with cap_id
  cap_id=""
  has_contract=false
  leveling=""
  stage=""
  verb=""
  object=""

  if head -1 "$md_file" | grep -q '^---$'; then
    frontmatter=$(sed -n '/^---$/,/^---$/p' "$md_file" | sed '1d;$d')
    cap_id=$(echo "$frontmatter" | grep '^cap_id:' | awk '{print $2}' | tr -d '"')
    leveling=$(echo "$frontmatter" | grep '^leveling:' | awk '{print $2}' | tr -d '"')
    stage=$(echo "$frontmatter" | grep '^stage:' | awk '{print $2}' | tr -d '"')
    verb=$(echo "$frontmatter" | grep '^verb:' | awk '{print $2}' | tr -d '"')
    object=$(echo "$frontmatter" | grep '^object:' | awk '{print $2}' | tr -d '"')
    if [ -n "$cap_id" ]; then
      has_contract=true
      CONTRACT_COUNT=$((CONTRACT_COUNT + 1))
    fi
  fi

  # Default leveling if not in frontmatter
  if [ -z "${leveling:-}" ]; then
    leveling="G3-V1-P2-M3"
  fi

  if [ "$has_contract" = true ]; then
    {
      echo ""
      echo "  ${cap_id}:"
      echo "    domain: core"
      echo "    stage: ${stage:-unknown}"
      echo "    verb: ${verb:-unknown}"
      echo "    object: ${object:-unknown}"
      echo "    leveling: ${leveling}"
      echo "    block: \"$block_path\""
      echo "    cap_contract: true"
    } >> "$CATALOG_FILE"
  else
    {
      echo ""
      echo "  # cap-???-${filename}: (no frontmatter, needs annotation)"
      echo "  # block: \"$block_path\""
    } >> "$CATALOG_FILE"
  fi
  CAP_COUNT=$((CAP_COUNT + 1))
done

echo ""
echo "=== Summary ==="
echo "Total capabilities:  $CAP_COUNT"
echo "With contracts:      $CONTRACT_COUNT"
echo "Output: $CATALOG_FILE"
echo ""
echo "Build complete!"
