#!/bin/bash
# Build Capability Index
# Regenerates _resolver/capability-index.yaml from block files.
#
# All entries use cap-<verb>-<object> format.
# Files with YAML frontmatter cap_id are marked with cap_contract: true.
#
# Usage: bash tools/build_capability_index.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_DIR/skills"
INDEX_FILE="$SKILLS_DIR/_resolver/capability-index.yaml"

echo "=== Build Capability Index ==="
echo "Skills dir: $SKILLS_DIR"
echo "Output: $INDEX_FILE"
echo ""

# Ensure _resolver directory exists
mkdir -p "$SKILLS_DIR/_resolver"

# Header
cat > "$INDEX_FILE" << 'HEADER'
# Capability Index — Maps cap-* IDs to block files
# Auto-generated by tools/build_capability_index.sh
#
# Format: cap-<verb>-<object> → list of block files
# When multiple blocks implement the same capability, resolver picks by leveling.
# Blocks with cap_contract: true have YAML frontmatter for contract validation.

capabilities:
HEADER

STAGES=(discover decide build verify deliver operate review knowledge)
CAP_COUNT=0
CONTRACT_COUNT=0

for stage in "${STAGES[@]}"; do
  sub_dir="$SKILLS_DIR/_stages/$stage/sub"
  if [ ! -d "$sub_dir" ]; then
    continue
  fi

  echo "  # === ${stage^^} ===" >> "$INDEX_FILE"
  echo "" >> "$INDEX_FILE"

  for md_file in "$sub_dir"/*.md; do
    [ -f "$md_file" ] || continue
    filename=$(basename "$md_file" .md)
    block_path="_stages/$stage/sub/$filename.md"

    # Check if file has YAML frontmatter with cap_id
    cap_id=""
    has_contract=false
    leveling=""
    if head -1 "$md_file" | grep -q '^---$'; then
      frontmatter=$(sed -n '/^---$/,/^---$/p' "$md_file" | sed '1d;$d')
      cap_id=$(echo "$frontmatter" | grep '^cap_id:' | awk '{print $2}' | tr -d '"')
      leveling=$(echo "$frontmatter" | grep '^leveling:' | awk '{print $2}' | tr -d '"')
      if [ -n "$cap_id" ]; then
        has_contract=true
        CONTRACT_COUNT=$((CONTRACT_COUNT + 1))
      fi
    fi

    # Default leveling if not in frontmatter
    if [ -z "${leveling:-}" ]; then
      leveling="G3-V1-P2-M3"
    fi

    if [ "$has_contract" = true ]; then
      echo "  ${cap_id}:" >> "$INDEX_FILE"
      echo "    - { block: \"$block_path\", leveling: \"$leveling\", stage: $stage, cap_contract: true }" >> "$INDEX_FILE"
    else
      # Generate cap-* ID from stage + filename
      echo "  # cap-???-${filename}: (no frontmatter, needs annotation)" >> "$INDEX_FILE"
      echo "  # - { block: \"$block_path\", leveling: \"$leveling\", stage: $stage }" >> "$INDEX_FILE"
    fi
    echo "" >> "$INDEX_FILE"
    CAP_COUNT=$((CAP_COUNT + 1))
  done
done

echo ""
echo "=== Summary ==="
echo "Total capabilities:  $CAP_COUNT"
echo "With contracts:      $CONTRACT_COUNT"
echo "Output: $INDEX_FILE"
echo ""
echo "Build complete!"
